apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.NAME }}-ingress"
  namespace: "{{ .Values.NAMESPACE }}"
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:8333205604:certficate/456das564-456dsa
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/subnets: subnet-ba45.subnet-ad123,subnet-ad313
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/wafv2-acl-id: "arn:aws:wafv2:us-west-2:8333205604:regional/webacl/MyRateLimitWebACL/abc123"  # Attach WAF WebACL
    nginx.ingress.kubernetes.io/limit-rps: "2"                 # 2 requests per second
    nginx.ingress.kubernetes.io/limit-rpm: "10"                # 10 requests per minute
    nginx.ingress.kubernetes.io/limit-connections: "1"         # Maximum number of connections per client
spec:
  ingressClassName: alb
  rules:
  - host: "employee.system.com"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: "{{ .Values.NAME }}-svc"
            port:
              number: 8081